test: add `loom` wrapper script
This commit adds a shell script, `bin/loom.sh`, which runs Loom tests
with default values for Loom's configuration variables.

The nightly Rust compiler is used to enable Loom's location tracking
support. This allows Loom to emit diagnostics that include the caller's
source code locations when errors occur. For example, after modifying
the code to cause an invalid concurrent mutable access, we get nice
panics like this:

```
---- pool::tests::concurrent_create_clear stdout ----

 ================== Iteration 1 ==================

~~~~~~~~ THREAD 1 ~~~~~~~~
thread 'pool::tests::concurrent_create_clear' panicked at '
Causality violation: Concurrent write accesses to `UnsafeCell`.
      created: src/page/mod.rs:131:19
    write one: thread #0 @ src/page/mod.rs:188:9
    write two: thread #1 @ src/page/mod.rs:188:9
', /home/eliza/.cargo/registry/src/github.com-1ecc6299db9ec823/loom-0.3.0/src/rt/location.rs:116:9

```

The tests are compiled in release mode to improve performance, but debug
assertions are enabled.

Any arguments to this script are passed to the `cargo test` invocation.

Signed-off-by: Eliza Weisman <eliza@buoyant.io>